import Config from 'react-native-config'

const configs = {
  ENV: Config.ENV,
  API_URL: Config.API_URL,
  CODE_PUSH_KEY_IOS: Config.CODE_PUSH_KEY_IOS,
  CODE_PUSH_KEY_ANDROID: Config.CODE_PUSH_KEY_ANDROID,
  GOOGLE_CLIENT_ID_ANDROID: Config.GOOGLE_CLIENT_ID_ANDROID,
  GOOGLE_CLIENT_ID_IOS: Config.GOOGLE_CLIENT_ID_IOS,
  NEWSAPI_KEY: 'b7fe8e8a4f004beaa5fe0cbc563e30e1',
  RAZOR_PAY_API_KEY: 'rzp_test_VX8h1EJO29zWMm',
  STRIPE_CLIENT_SECRET: Config.STRIPE_CLIENT_SECRET,
  STRIPE_PUBLISHABLE_KEY: Config.STRIPE_PUBLISHABLE_KEY
}

export default configs
