export const FETCH_NEWS_PENDING = 'FETCH_NEWS_PENDING'
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS'
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED'
export const CLEAR_REDUX = 'CLEAR_REDUX'
