require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

pod 'Google-Maps-iOS-SDK', '~> 1.9.2'

abstract_target 'App' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
  target 'RNBoilerplate' do
    #Production-specific pods
  end

  target 'DevRNBoilerplate' do
    #Development-specific pods
  end
  
  target 'StagRNBoilerplate' do
    #Staging-specific pods
  end
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.75.1' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
