import languagekeys from './languagekeys'

const ar = {
  [languagekeys.login]: 'تسجيل الدخول',
  [languagekeys.emailAddress]: 'البريد الإلكتروني',
  [languagekeys.password]: 'كلمة المرور',
  [languagekeys.general]: 'عام',
  [languagekeys.business]: 'أعمال',
  [languagekeys.entertainment]: 'ترفيه',
  [languagekeys.health]: 'صحة',
  [languagekeys.science]: 'علوم',
  [languagekeys.sports]: 'رياضة',
  [languagekeys.technology]: 'تكنولوجيا',
  [languagekeys.errorHeader]: 'حدث خطأ',
  [languagekeys.errorMessage]: 'الرجاء التحقق من اتصالك بالإنترنت',
  [languagekeys.retry]: 'إعادة المحاولة',
  [languagekeys.changeLanguage]: 'تغيير اللغة',
  [languagekeys.submit]: 'إرسال',
  [languagekeys.youcanchange]: 'يمكنك تغيير اللغة من هنا.',
  [languagekeys.changePassword]: 'تغيير كلمة المرور',
  [languagekeys.dashboard]: 'لوحة التحكم',
  [languagekeys.currentPassword]: 'كلمة المرور الحالية',
  [languagekeys.newPassword]: 'كلمة المرور الجديدة',
  [languagekeys.confirmNewPassword]: 'تأكيد كلمة المرور الجديدة',
  [languagekeys.passwordValidation]:
    'يجب أن تحتوي كلمة المرور على حرف كبير وحرف صغير وحرف خاص ورقم واحد على الأقل',
  [languagekeys.forgotPassword]: 'نسيت كلمة المرور',
  [languagekeys.goBackLogin]: 'العودة إلى تسجيل الدخول',
  [languagekeys.signup]: 'إنشاء حساب',
  [languagekeys.alreadyHaveAccount]: 'هل لديك حساب بالفعل؟',
  [languagekeys.pickImage]: 'اختيار صورة',
  [languagekeys.createAccount]: 'إنشاء حساب',
  [languagekeys.resendCode]: 'إعادة إرسال رمز التفويض',
  [languagekeys.verificationCode]: 'التحقق من رمز التفويض',
  [languagekeys.dontHaveAccount]: 'ليس لديك حساب؟',
  [languagekeys.registerHere]: 'سجل هنا',
  [languagekeys.loginWithOtp]: 'تسجيل الدخول بواسطة رمز التفويض',
  [languagekeys.editProfile]: 'تعديل الملف الشخصي',
  [languagekeys.googlePay]: 'جوجل يدفع',
  [languagekeys.payWithGooglePay]: 'الدفع باستخدام جوجل يدفع',
  [languagekeys.paywithRazorPay]: 'الدفع باستخدام موس الحلاقة يدفع',
  [languagekeys.payWithStripe]: 'الدفع باستخدام شريط',
  [languagekeys.googleMap]: 'خرائط جوجل',
  [languagekeys.todo]: 'قائمة المهام',
  [languagekeys.pin]: 'رمز الأمان',
  [languagekeys.addTodo]: 'إضافة مهمة',
  [languagekeys.updateTodo]: 'تحديث المهمة',
  [languagekeys.chat]: 'الدردشة',
  [languagekeys.payment]: 'الدفع',
  [languagekeys.userProfile]: 'ملف المستخدم',
  [languagekeys.security]: 'الأمان',
  [languagekeys.notification]: 'الإشعارات',
  [languagekeys.privacy]: 'الخصوصية',
  [languagekeys.subscription]: 'اشتراكي',
  [languagekeys.helpSupports]: 'المساعدة والدعم',
  [languagekeys.termsConditions]: 'الشروط والسياسات',
  [languagekeys.freeUpSpaces]: 'تحرير المساحة',
  [languagekeys.dataSaver]: 'توفير البيانات',
  [languagekeys.reportProblem]: 'الإبلاغ عن مشكلة',
  [languagekeys.addAccount]: 'إضافة حساب',
  [languagekeys.account]: 'الحساب',
  [languagekeys.support]: 'الدعم وحول',
  [languagekeys.caches]: 'الذاكرة المخبأة',
  [languagekeys.action]: 'الإجراءات',
  [languagekeys.logout]: 'تسجيل الخروج',
  [languagekeys.deleteTodo]: 'حذف المهمة',
  [languagekeys.areYouSure]: 'هل أنت متأكد؟',
  [languagekeys.ok]: 'موافق',
  [languagekeys.cancel]: 'إلغاء',
  [languagekeys.success]: 'نجاح',
  [languagekeys.error]: 'خطأ',
  [languagekeys.pinCodeScreen.biometricsPromptMessage]: 'المصادقة باستخدام القياسات الحيوية الخاصة بك',
  [languagekeys.pinCodeScreen.correctPin]: 'تم قبول رمز PIN!',
  [languagekeys.pinCodeScreen.invalidPinMessage]: 'يجب أن يتكون رقم التعريف الشخصي من 4 أرقام.',
  [languagekeys.pinCodeScreen.errorMessage]: 'حدث خطأ ما',
  [languagekeys.pinCodeScreen.incorrectPin]: 'رمز PIN غير صحيح. يرجى المحاولة مرة أخرى.',
  [languagekeys.pinCodeScreen.successMessage]: 'تم التوثيق بنجاح!',
  [languagekeys.pinCodeScreen.enablePinText]: 'تمكين رمز التعريف الشخصي',
  [languagekeys.pinCodeScreen.enterPinTitle]: 'أدخل رمز التعريف الشخصي',
  [languagekeys.pinCodeScreen.submit]: 'إرسال',
}

export default ar
