import languagekeys from './languagekeys'

const en = {
  [languagekeys.login]: 'Login',
  [languagekeys.emailAddress]: 'Email',
  [languagekeys.password]: 'Password',
  [languagekeys.general]: 'general',
  [languagekeys.business]: 'business',
  [languagekeys.entertainment]: 'entertainment',
  [languagekeys.health]: 'health',
  [languagekeys.science]: 'science',
  [languagekeys.sports]: 'sports',
  [languagekeys.technology]: 'technology',
  [languagekeys.errorHeader]: 'Something went wrong',
  [languagekeys.errorMessage]: 'Please check your internet connection',
  [languagekeys.retry]: 'Retry',
  [languagekeys.changeLanguage]: 'Change Language',
  [languagekeys.submit]: 'Submit',
  [languagekeys.youcanchange]: 'You can change your language from here.',
  [languagekeys.changePassword]: 'Change Password',
  [languagekeys.dashboard]: 'Dashboard',
  [languagekeys.currentPassword]: 'Current Password',
  [languagekeys.newPassword]: 'New Password',
  [languagekeys.confirmNewPassword]: 'Confirm New Password',
  [languagekeys.passwordValidation]:
    'Password must contain atleast 1 upper case, 1 lower case letter, 1 special chracter and 1 number',
  [languagekeys.forgotPassword]: 'Forgot Password?',
  [languagekeys.submit]: 'Submit',
  [languagekeys.goBackLogin]: 'Go back to login',
  [languagekeys.signup]: 'Sign Up',
  [languagekeys.alreadyHaveAccount]: 'Already have an account?',
  [languagekeys.pickImage]: 'Pick Image',
  [languagekeys.createAccount]: 'Create Account',
  [languagekeys.resendCode]: 'Resend OTP in',
  [languagekeys.resend]: 'Resend OTP',
  [languagekeys.verificationCode]: 'Verify the Authorisation Code',
  [languagekeys.dontHaveAccount]: `Don't have an Account?`,
  [languagekeys.registerHere]: 'Register here',
  [languagekeys.loginWithOtp]: 'Login With Otp',
  [languagekeys.editProfile]: 'Edit Profile',
  [languagekeys.googlePay]: 'Google Pay',
  [languagekeys.payWithGooglePay]: 'Pay with Google Pay',
  [languagekeys.paywithRazorPay]: 'Pay with Razor Pay',
  [languagekeys.payWithStripe]: 'Pay using Stripe',
  [languagekeys.googleMap]: 'Google Map',
  [languagekeys.todo]: 'Todo List',
  [languagekeys.pin]: 'Security Pin',
  [languagekeys.addTodo]: 'Add Todo',
  [languagekeys.updateTodo]: 'Update Todo',
  [languagekeys.chat]: 'Chat',
  [languagekeys.payment]: 'Payment',
  [languagekeys.userProfile]: 'User Profile',
  [languagekeys.security]: 'Security',
  [languagekeys.notification]: 'Notification',
  [languagekeys.privacy]: 'Privacy',
  [languagekeys.subscription]: 'My Subscription',
  [languagekeys.helpSupports]: 'Help & Support',
  [languagekeys.termsConditions]: 'Terms & Policies',
  [languagekeys.freeUpSpaces]: 'Free Up Space',
  [languagekeys.dataSaver]: 'Data Saver',
  [languagekeys.reportProblem]: 'Report a problem',
  [languagekeys.addAccount]: 'Add Account',
  [languagekeys.account]: 'Account',
  [languagekeys.support]: 'Support & About',
  [languagekeys.caches]: 'Caches',
  [languagekeys.action]: 'Actions',
  [languagekeys.logout]: 'Logout',
  [languagekeys.deleteTodo]: 'Delete Todo',
  [languagekeys.areYouSure]: 'Are you sure?',
  [languagekeys.ok]: 'Ok',
  [languagekeys.cancel]: 'Cancel',
  [languagekeys.pinCodeScreen.enablePinText]: 'Enable PIN Code',
  [languagekeys.pinCodeScreen.enterPinTitle]: 'Enter PIN Code',
  [languagekeys.pinCodeScreen.submit]: 'Submit',
  [languagekeys.success]: 'Success',
  [languagekeys.error]: 'Error',
  [languagekeys.pinCodeScreen.biometricsPromptMessage]: 'Authenticate with your biometrics',
  [languagekeys.pinCodeScreen.correctPin]:'PIN code is correct!',
  [languagekeys.pinCodeScreen.invalidPinMessage]: 'PIN must be a 4-digit number.',
  [languagekeys.pinCodeScreen.errorMessage]:'Something went wrong',
  [languagekeys.pinCodeScreen.incorrectPin]:'Incorrect PIN code. Please try again.',
  [languagekeys.pinCodeScreen.successMessage]:'Authentication successful!',
  [languagekeys.title1]: 'Title:',
  [languagekeys.description]: 'Description:',
  [languagekeys.title]: 'ReactNative Boilerplate',
  [languagekeys.entername]: 'Enter your name',
  [languagekeys.enteremail]: 'Enter your email',
  [languagekeys.enterpass]: 'Enter your password',
  [languagekeys.reenterpass]: 'Re-Enter your password',
  [languagekeys.enterphone]: 'Enter phone number',
  [languagekeys.entertitle]: 'Enter todo title',
  [languagekeys.enterdes]: 'Enter todo description',
  [languagekeys.editsucess]: 'Todo updated successfully!',
  [languagekeys.addsucess]: 'Todo added successfully!',
  [languagekeys.tododelete]: 'Todo deleted successfully!',
  [languagekeys.validtodo]: 'Please enter a valid todo'
}

export default en
