import languagekeys from './languagekeys'

const hin = {
  [languagekeys.login]: 'लॉगइन',
  [languagekeys.email]: 'ईमेल',
  [languagekeys.password]: 'पासवर्ड',
  [languagekeys.changeLanguage]: 'भाषा बदलो',
  [languagekeys.submit]: 'प्रस्तुत',
  [languagekeys.youcanchange]: 'आप यहां से अपनी भाषा बदल सकते हैं।',
  [languagekeys.general]: 'सामान्य',
  [languagekeys.business]: 'व्यापार',
  [languagekeys.dashboard]: 'डैशबोर्ड',
  [languagekeys.entertainment]: 'मनोरंजन',
  [languagekeys.health]: 'स्वास्थ्य',
  [languagekeys.science]: 'विज्ञान',
  [languagekeys.sports]: 'खेल',
  [languagekeys.technology]: 'प्रौद्योगिकी',
  [languagekeys.errorHeader]: 'कुछ गलत हो गया',
  [languagekeys.errorMessage]: 'कृपया अपना इंटरनेट कनेक्शन जांचें',
  [languagekeys.retry]: 'पुन: प्रयास करें',
  [languagekeys.changePassword]: 'पासवर्ड बदलें',
  [languagekeys.currentPassword]: 'वर्तमान पासवर्ड',
  [languagekeys.newPassword]: 'वर्तमान पासवर्ड',
  [languagekeys.confirmNewPassword]: 'नए पासवर्ड की पुष्टि करें',
  [languagekeys.passwordValidation]:
    'पासवर्ड में कम से कम 1 अपर केस अक्षर, 1 लोअर केस अक्षर, 1 विशेष अक्षर और 1 संख्या होनी चाहिए',
  [languagekeys.forgotPassword]: 'पासवर्ड भूल गए',
  [languagekeys.goBackLogin]: 'लॉगिन करने के लिए वापस जाएँ',
  [languagekeys.alreadyHaveAccount]: 'पहले से ही खाता है?',
  [languagekeys.signup]: 'साइन अप करें',
  [languagekeys.pickImage]: 'छवि चुनें',
  [languagekeys.createAccount]: 'खाता बनाएं',
  [languagekeys.resendCode]: 'प्राधिकरण कोड पुनः भेजें',
  [languagekeys.verificationCode]: 'प्राधिकरण कोड सत्यापित करें',
  [languagekeys.registerHere]: 'यहां रजिस्टर करें',
  [languagekeys.dontHaveAccount]: 'खाता नहीं है?',
  [languagekeys.loginWithOtp]: 'ओटीपी से लॉगिन करें',
  [languagekeys.editProfile]: 'प्रोफ़ाइल संपादित करें',
  [languagekeys.googlePay]: 'गूगल पे',
  [languagekeys.payWithGooglePay]: 'गूगल पे से भुगतान करें',
  [languagekeys.paywithRazorPay]: 'रेजर पे से भुगतान करें',
  [languagekeys.payWithStripe]: 'स्ट्राइप',
  [languagekeys.googleMap]:'गूगल नक़्शे',
  [languagekeys.todo]:'टू-डू सूची',
  [languagekeys.addTodo]:'कार्य जोड़ें',
  [languagekeys.updateTodo]:'कार्य अद्यतन करें'
  
}

export default hin
