const languagekeys = {
  login: 'Login',
  password: 'Password',
  emailAddress: 'Email',
  changeLanguage: 'changelanguage',
  submit: 'submit',
  general: 'general',
  business: 'business',
  entertainment: 'entertainment',
  health: 'health',
  science: 'science',
  sports: 'sports',
  technology: 'technology',
  errorHeader: 'errorHeader',
  errorMessage: 'errorMessage',
  retry: 'retry',
  changePassword: 'changePassword',
  dashboard: 'dashboard',
  currentPassword: 'currentPassword',
  newPassword: 'newPassword',
  confirmNewPassword: 'confirmNewPassword',
  passwordValidation: 'passwordValidation',
  forgotPassword: 'forgotPassword',
  goBackToLogin: 'goBackToLogin',
  signup: 'signup',
  alreadyHaveAccount: 'alreadyHaveAccount',
  pickImage: 'pickImage',
  createAccount: 'createAccount',
  resendCode: 'resendCode',
  verificationCode: 'verificationCode',
  registerHere: 'registerHere',
  dontHaveAccount: 'dontHaveAccount',
  loginWithOtp: 'loginWithOtp',
  editProfile: 'editProfile',
  googlePay: 'googlePay',
  payWithGooglePay: 'payWithGooglePay',
  paywithRazorPay: 'payWithRazorPay'
}

export default languagekeys
